config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index', as: :index
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
	def index
		@cocktails = Cocktail.all
	end

	def show
		@cocktail = Cocktail.find(params[:id])
		@dose = Dose.new
	end

	def new
		@cocktail = Cocktail.new
	end

	def create
		@cocktail = Cocktail.new(cocktail_params)
		@cocktail.save
		redirect_to index_path
	end

	private

	def cocktail_params
		params.require(:cocktail).permit(:name, :photo)
	end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
	def new
	end
	
	def create
		@cocktail = Cocktail.find(params[:cocktail_id])
		@dose = Dose.new(dose_params)
		@dose.cocktail = @cocktail
		if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
	end

	def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

	private

	def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1491333078588-55b6733c7de6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>Mahoney's Bar </h1>
    <p>You are welcome to create your own drink in my bar! </p>
  </div>
</div>
<div class="container">

<div class="cards mt-3">
    <% @cocktails.each do |cocktail| %>
      <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo.key %>)">
        <p><%= link_to "#{cocktail.name}", cocktail_path(cocktail) %></p>
      </div>
    <%end%>
  </div>

  <% cl_image_tag "p1yhv3sdcqgeekigrwgd" %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
    <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name , class: "c-w"%>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-secondary" %>
    <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1 class="show-image"><%=  cl_image_tag(@cocktail.photo.key,
        width: 400, height: 300, crop: :fill) %></h1>

  <h3>Doses</h3>
  <% @cocktail.doses.each do |dose| %>
    <p>Description: <%=dose.description%> / Ingredient: <%=dose.ingredient.name%><%= link_to dose_path(dose),
    method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-remove-link' do %>
    <i class="fas fa-trash"></i><% end %></p>
  <% end %>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add a Dose!", class: "btn btn-secondary" %>
  <% end %>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-light bg-dark">
  <a class="navbar-brand" id="font-link" href="/"><i class="fas fa-glass-martini-alt"></i></a>
  <div class="btn btn-primary bg-dark border border-light"><%= link_to "Add a Drink", new_cocktail_path%></div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>